k apply -f github/simple-pipeline/
k apply -f github1/simple-pipeline/
k apply -f github2/simple-pipeline/
k apply -f github3/simple-pipeline/
k apply -f github4/simple-pipeline/
k apply -f github5/simple-pipeline/
k apply -f github6/simple-pipeline/
k apply -f github7/simple-pipeline/
k apply -f github8/simple-pipeline/
k apply -f github9/simple-pipeline/
k apply -f github10/simple-pipeline/
k apply -f github11/simple-pipeline/
k apply -f github12/simple-pipeline/